: CELLS CELL * ; INLINE
: BL #32 ; INLINE
: SPACE BL EMIT ; INLINE
: CR #13 EMIT #10 EMIT ;
: . (.) SPACE ;

: ?COMPILING STATE @ ;   INLINE

: IF   ?COMPILING .IF BRANCHFZ HERE 0 C, .THEN ; .IMMEDIATE.
: ELSE ?COMPILING .IF BRANCHF  HERE 0 C, SWAP HERE OVER - SWAP C! .THEN ; .IMMEDIATE.
: THEN ?COMPILING .IF                         HERE OVER - SWAP C! .THEN ; .IMMEDIATE.

: LEAVE ?COMPILING IF RET THEN ;    IMMEDIATE

: BEGIN ?COMPILING IF HERE THEN ;    IMMEDIATE
: AGAIN ?COMPILING IF JMP   , THEN ;    IMMEDIATE
: WHILE ?COMPILING IF JMPNZ , THEN ;    IMMEDIATE
: UNTIL ?COMPILING IF JMPZ  , THEN ;    IMMEDIATE
\ .QUIT

: COUNT DUP 1+ SWAP C@ ;
: TYPE
	BEGIN
		DUP NOT IF
			DROP DROP LEAVE
		THEN
		SWAP DUP C@ EMIT 1+ 
		SWAP 1-
	AGAIN ;

: TRUE -1 ; INLINE

: EXECUTE-WORD DROP >R ;

VARIABLE (line)
: LINE (line) @ ;

\ (  -- )
: EXECUTE-LINE
	BEGIN
		LINE
		GET-WORD (line) ! CR .s 
		IF 
			FIND-WORD .s 
			IF 
				EXECUTE-WORD .s
			ELSE
				DROP
			THEN
		THEN
	AGAIN ;

: ok SPACE .S S"  ok. " COUNT TYPE ;
: hello S" Hello." COUNT TYPE ;

: main hello
	BEGIN
		ok 
		HERE $0100 + (line) !
		0 LINE 1-
		GET-LINE DROP
		LINE EXECUTE-LINE
	AGAIN ;
 
: count-to 
	S" counting to " COUNT TYPE
	GETTICK
	#500000000 DUP .
	BEGIN
		1- DUP
	WHILE 
	DROP 
	GETTICK OVER OVER SWAP -
	S" done." COUNT TYPE .S ;

1 LOAD
\ 2 LOAD
\ 'a' DUP .S . SPACE EMIT '!' EMIT CR
