: CELLS CELL * ; INLINE
: BL #32 ; INLINE
: SPACE BL EMIT ; INLINE
: CR #13 EMIT #10 EMIT ;
: . (.) SPACE ;

: ?COMPILING STATE @ ;   INLINE

: IF   ?COMPILING .IF BRANCHFZ HERE 0 C, .THEN ; .IMMEDIATE.
: ELSE ?COMPILING .IF BRANCHF  HERE 0 C, SWAP HERE OVER - SWAP C! .THEN ; .IMMEDIATE.
: THEN ?COMPILING .IF                         HERE OVER - SWAP C! .THEN ; .IMMEDIATE.

: LEAVE ?COMPILING IF RET THEN ;    IMMEDIATE

: BEGIN ?COMPILING IF HERE DUP . THEN ;    IMMEDIATE
: AGAIN ?COMPILING IF JMP   , THEN ;    IMMEDIATE
: WHILE ?COMPILING IF DUP . JMPNZ , THEN ;    IMMEDIATE
: UNTIL ?COMPILING IF JMPZ  , THEN ;    IMMEDIATE
\ .QUIT

: COUNT DUP 1+ SWAP C@ ;
: TYPE
	BEGIN
		DUP NOT IF
			DROP DROP LEAVE
		THEN
		SWAP DUP C@ EMIT 1+ 
		SWAP 1-
	AGAIN ;

: TRUE -1 ; INLINE

: ok SPACE S" OK " COUNT TYPE .S CR ;
: hello S" Hello." COUNT TYPE ;

: REPL
    BEGIN
        ok
        GET-LINE
        EXECUTE-LINE
        BYE
    AGAIN ;

: user-line HERE 100 + 0 OVER GET-LINE DROP ;
: main hello ok user-line 1+ EXECUTE-LINE 555 . ok BYE ;
hello 
: count-to 
	S" counting to " COUNT TYPE
	GETTICK
	#500000000 DUP .
	BEGIN
		1- DUP
	WHILE 
	DROP 
	GETTICK OVER OVER SWAP -
	S" done." COUNT TYPE .S ;

1 LOAD
\ 2 LOAD

'a' DUP .S . SPACE EMIT '!' EMIT CR
